"""Security, input sanitization, and PII access control modules."""

from security.access_control import AccessControlGuard
from security.pre_extraction import (
    PreExtractionClassifier,
    classify_inbound_demand,
    detect_intents,
    detect_legal_threat_or_hostility,
    detect_out_of_scope,
    extract_sub_queries,
)
from security.sanitizer import (
    CONTROL_CHARS_PATTERN,
    EMAIL_PATTERN,
    INJECTION_PATTERNS,
    ORDER_ID_PATTERN,
    SPOOFED_TAG_PATTERN,
    STRICT_EMAIL_PATTERN,
    STRICT_ORDER_ID_PATTERN,
    TAG_REMOVAL_TOKEN,
    USER_EMAIL_TAG_PATTERN,
    detect_prompt_injection,
    extract_all_emails,
    extract_all_order_ids,
    extract_email,
    extract_entities,
    extract_order_id,
    is_valid_email,
    is_valid_order_id,
    sanitize_tag_spoofing,
    scrub_control_characters,
    wrap_user_email_payload,
)

__all__ = [
    "AccessControlGuard",
    "CONTROL_CHARS_PATTERN",
    "EMAIL_PATTERN",
    "INJECTION_PATTERNS",
    "ORDER_ID_PATTERN",
    "PreExtractionClassifier",
    "SPOOFED_TAG_PATTERN",
    "STRICT_EMAIL_PATTERN",
    "STRICT_ORDER_ID_PATTERN",
    "TAG_REMOVAL_TOKEN",
    "USER_EMAIL_TAG_PATTERN",
    "classify_inbound_demand",
    "detect_intents",
    "detect_legal_threat_or_hostility",
    "detect_out_of_scope",
    "detect_prompt_injection",
    "extract_all_emails",
    "extract_all_order_ids",
    "extract_email",
    "extract_entities",
    "extract_order_id",
    "extract_sub_queries",
    "is_valid_email",
    "is_valid_order_id",
    "sanitize_tag_spoofing",
    "scrub_control_characters",
    "wrap_user_email_payload",
]
