"""LLM response, tool calling, and token telemetry models."""

from typing import Any

from pydantic import Field

from models.base import BaseDTO

__all__ = ["LLMResponse", "LLMToolCall", "LLMUsage"]


class LLMToolCall(BaseDTO):
    """Normalized tool call request generated by the LLM."""

    id: str
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class LLMUsage(BaseDTO):
    """Inference token consumption and FinOps cost metrics."""

    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    cost_usd: float = Field(default=0.0, ge=0.0)


class LLMResponse(BaseDTO):
    """Container for model output, tool requests, and token telemetry."""

    content: str | None = None
    tool_calls: tuple[LLMToolCall, ...] = Field(default_factory=tuple)
    usage: LLMUsage = Field(default_factory=LLMUsage)
    model: str = ""
    finish_reason: str = "stop"

    @property
    def has_tool_calls(self) -> bool:
        """Check whether the model requested any tool executions."""
        return len(self.tool_calls) > 0

    @property
    def first_tool_call(self) -> LLMToolCall | None:
        """Return the first requested tool call, if present."""
        return self.tool_calls[0] if self.tool_calls else None
